### ISSUE TITLE
Suggestion|Suggestion: Add emails to data

### ISSUE THREAD

**Issue by shawnthompson** [esdcskp-edscpcs/skp#6]
### Overview | Aperçu

The [Security Champions](https://esdcskp-edscpcs.github.io/skp/security-champions/) page does not validate because you are not linking to actual emails.

Suggestion would to either put their emails address in the `_data` yml or remove the link completely.

### References | Références

If you validate the page using the W3C validation tool you will see 

> Bad value mailto:Mailloux, Annick [NC] for attribute href on element a: Illegal character in scheme data: space is not allowed.
> From line 307, column 42; to line 307, column 80
> `primary"><a href="mailto:Mailloux, Annick [NC]">Maillo`

**Comment by lafeeflushette** [comment]
Makes sense, thanks!
